[package]
name = "blockchain"
version = "0.1.0"
authors = ["Naokisato <821874555@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.126"
bincode = "1.3.3"
chrono = "*"
rust-crypto = "*"
