[package]
name = "blockchain"
version = "0.1.0"
authors = ["Naokisato <821874555@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.106"
bincode = "1.2.1"
